### ISSUE TITLE
Add a login screen to the app

### ISSUE THREAD

**Issue by r0hnx** [r0hnx/github_clone#1]
* Login screen similar to **Github**

**Comment by akshay512** [comment]
can u share ui image

**Comment by r0hnx** [comment]
* Sign In 1:
![image](https://user-images.githubusercontent.com/31055475/95592310-10d0e680-0a66-11eb-9c4c-6e6fdec04a5e.png)

* Sign In 2:
![image](https://user-images.githubusercontent.com/31055475/95592177-e7b05600-0a65-11eb-88aa-a235069fe9b0.png)

**Comment by r0hnx** [comment]
[Design Inspiration](https://dribbble.com/shots/11103636-Github-App-Redesign-Concept)

**Comment by akshay512** [comment]
I referred that one itself

**Comment by akshay512** [comment]
Just came across that when searching

**Comment by r0hnx** [comment]
Login Screen Added in #4

**Comment by akshay512** [comment]
thanks!!!
