### ISSUE TITLE
Add a home screen to the app

### ISSUE THREAD

**Issue by r0hnx** [r0hnx/github_clone#2]
* Same as the home screen from GitHub app

![image](https://user-images.githubusercontent.com/31055475/95558486-ecf4ad00-0a33-11eb-9cd7-1c85d8503e30.png)

**Comment by tushar-suthar** [comment]
is this just making home screen or adding functionality to it also

**Comment by r0hnx** [comment]
@code-netizen Right now just making the homescreen, we'll add functionality later.

**Comment by EANimesha** [comment]
Is anyone asigned? If not I can do this.

**Comment by r0hnx** [comment]
Ok @EANimesha , for design guidelines go through README.md
