### ISSUE TITLE
Add a navbar to the main screen

### ISSUE THREAD

**Issue by r0hnx** [r0hnx/github_clone#3]
**Similar to this**

![image](https://user-images.githubusercontent.com/31055475/95558643-2fb68500-0a34-11eb-84e8-2970e30e94a8.png)

**Comment by tushar-suthar** [comment]
is dart accepted for this, i want to work on this

**Comment by r0hnx** [comment]
Yes, @code-netizen the whole project is dart based.

**Comment by tushar-suthar** [comment]
i have made PR for bottom navigation bar

**Comment by r0hnx** [comment]
Navigation Bar Added in #6
