### ISSUE TITLE
Design models and APIs for fetching data from Github

### ISSUE THREAD

**Issue by r0hnx** [r0hnx/github_clone#8]
should fetch 
- Authorised User Details
- Issues
- Repositories
- Pull Request
- Recent Activities
- Favourite
- Organizations
- Notification
- Explore

**Comment by hiashutoshsingh** [comment]
Hey @r0hnx i could take some part of this app, What can i take let me know ?

**Comment by r0hnx** [comment]
@hiashutoshsingh , get familiar with the GitHub API's [here](https://developer.github.com/v3/) and create the models for the data that would be fetched. Also can check [this](https://api.github.com) for reference.

**Comment by hiashutoshsingh** [comment]
so you want me to created only models for all above mentioned features ?

**Comment by r0hnx** [comment]
> so you want me to created only models for all above mentioned features ?

Models and their respective functions to fetch data from the API

**Comment by rheakashyap** [comment]
I would like to work on this
